spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/droovedb
spring.datasource.password=raja2019
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update
spring.security.oauth2.client.registration.github.client-id=Ov23liSlqgbFGSNSFzoy
spring.security.oauth2.client.registration.github.client-secret=96047ee9158a69dd28e552add1517a38a5a597fb
spring.jpa.show-sql=true

