spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/droovedb
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update
spring.security.oauth2.client.registration.github.client-id=${GH_OAUTH2_ID}
spring.security.oauth2.client.registration.github.client-secret=${GH_OAUTH2_SEC}
spring.jpa.show-sql=true

