spring.application.name=trip-service
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/droovedb?currentSchema=trips_svc
spring.jpa.properties.hibernate.default_schema=trips_svc
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update
